name: Bambu Lab OTA Automation

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 */14 * *'
  workflow_dispatch:

jobs:
  run_bambu_lab_ota:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      
    env:
      BAMBU_ACCOUNT: ${{ secrets.BAMBU_ACCOUNT }}
      BAMBU_PASSWORD: ${{ secrets.BAMBU_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: pip install requests PyGithub

    - name: Check if branch exists
      id: check-branch
      run: |
        if git ls-remote --heads origin schedule-update | grep schedule-update; then
          echo "Branch exists"
        else
          git checkout -b schedule-update
          git push origin schedule-update
        fi

    - name: Run Bambu Lab OTA Script
      run: python scripts/bambu_firmware_ota.py
