name: Fetch Firmware

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Weekly (every Sunday)

permissions:
  contents: write
  pull-requests: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install Dependencies
        run: pip install aiohttp beautifulsoup4
      
      - name: Run Script
        run: python scripts/fetch.py
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: 'assets/*.json'
          commit-message: 'Firmware info updated'
          branch: fetch-firmware
          title: 'Firmware info updated'
          reviewers: lunDreame, yeorinhieut
          body: |
            ## Firmware Info Update
            This pull request contains the latest firmware info fetched from the server.

            **Summary of changes:**
            - Updated JSON files located in the `assets` directory.

            Please review and approve.
